"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { ArrowDownToLine, CalendarDays, Camera, CheckCircle2, Database, FileSpreadsheet, GitCompareArrows, Landmark, LoaderCircle, RefreshCw, Save, ScanText, ShieldCheck, TrendingDown, TrendingUp, Upload } from "lucide-react";
import { toast } from "sonner";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Progress } from "@/components/ui/progress";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Toaster } from "@/components/ui/sonner";
import { PortfolioCostCharts } from "@/components/portfolio-cost-charts";
import { getPositionCostShare } from "@/lib/portfolio-analytics";
import { CLASSIFICATION_LABELS } from "@/lib/position-classification";

type Position = { id:number; assetCode:string|null; assetName:string; assetType:string; currency:string; units:number; avgCost:number; marketPrice:number; costBasisTwd:number; marketValueTwd:number; pnlTwd:number; returnPct:number; dividendTwd:number; valuationDate:string|null; lastPurchaseDate:string|null; purchaseDateBasis:"exact"|"lower_bound"|"unknown"; assetCategory:string|null; investRegion:string|null; marketCapTier:string|null; investStyle:string|null; industryTheme:string|null; riskRewardLevel:"RR1"|"RR2"|"RR3"|"RR4"|"RR5"|null; sourceKind:string };
type ImportRow = { id:number; filename:string; sourceKind:string; rowCount:number; asOfDate:string|null; status:"pending"|"applied"; parserVersion:number; createdAt:string };
type OcrRow = { id:number; filename:string; docType:string; confidence:number; reviewStatus:string; createdAt:string };
type Totals = { positionCount:number; costBasisTwd:number; marketValueTwd:number; pnlTwd:number; dividendTwd:number };
type PortfolioSide = { asOfDate:string|null; dataAsOf:string|null; totals:Totals; importsUsed:Pick<ImportRow,"id"|"filename"|"sourceKind"|"asOfDate"|"rowCount">[] };
type PortfolioPayload = PortfolioSide & { positions:Position[]; imports:ImportRow[]; ocrDocuments:OcrRow[]; availableDates:string[] };
type ComparisonPayload = { from:PortfolioSide; to:PortfolioSide; metrics:{key:string;label:string;from:number;to:number;delta:number}[] };
type CanonicalRow = Omit<Position,"id"|"sourceKind"|"lastPurchaseDate"|"purchaseDateBasis"|"assetCategory"|"investRegion"|"marketCapTier"|"investStyle"|"industryTheme"|"riskRewardLevel"> & { raw:Record<string,string> };
const money = new Intl.NumberFormat("zh-TW",{style:"currency",currency:"TWD",maximumFractionDigits:0});
const num = (v:unknown) => Number(String(v??"0").replace(/[,%+\s]/g,""))||0;
const isIsoDate = (v:string) => /^\d{4}-\d{2}-\d{2}$/.test(v);
const taipeiToday = () => new Date().toLocaleDateString("en-CA",{timeZone:"Asia/Taipei"});
const EMPTY_TOTALS:Totals = {positionCount:0,costBasisTwd:0,marketValueTwd:0,pnlTwd:0,dividendTwd:0};
const EMPTY_SIDE:PortfolioSide = {asOfDate:null,dataAsOf:null,totals:EMPTY_TOTALS,importsUsed:[]};
const importSources = (side:PortfolioSide) => side.importsUsed.length?side.importsUsed.map(i=>`${i.filename}（${i.sourceKind}·${i.rowCount} 筆）`).join("、"):"尚無已套用批次";
async function fetchPortfolioPayload():Promise<PortfolioPayload>{
  const r=await fetch("/api/portfolio",{cache:"no-store"});
  const p=await r.json();
  if(!r.ok)throw new Error(p.error??"資料讀取失敗");
  return p as PortfolioPayload;
}
const labelOf = (group:keyof typeof CLASSIFICATION_LABELS,value:string|null) => value ? ((CLASSIFICATION_LABELS[group] as Record<string,string>)[value] ?? value) : null;
const classificationLabels = (p:Position) => [
  labelOf("assetCategory",p.assetCategory),
  p.investRegion!=="unknown"&&p.investRegion!=="not_applicable"?labelOf("investRegion",p.investRegion):null,
  p.marketCapTier!=="unknown"&&p.marketCapTier!=="not_applicable"?labelOf("marketCapTier",p.marketCapTier):null,
  p.investStyle!=="unknown"&&p.investStyle!=="not_applicable"?labelOf("investStyle",p.investStyle):null,
  p.industryTheme!=="unknown"&&p.industryTheme!=="not_applicable"?labelOf("industryTheme",p.industryTheme):null,
  p.riskRewardLevel?`風險報酬 ${p.riskRewardLevel}`:null,
].filter((x):x is string=>Boolean(x));

function parseCsv(text:string){
  const rows:string[][]=[]; let row:string[]=[],field="",quoted=false;
  for(let i=0;i<text.length;i++){const c=text[i]; if(c==='"'&&quoted&&text[i+1]==='"'){field+='"';i++;}else if(c==='"')quoted=!quoted;else if(c===","&&!quoted){row.push(field.trim());field="";}else if((c==="\n"||c==="\r")&&!quoted){if(c==="\r"&&text[i+1]==="\n")i++;row.push(field.trim());field="";if(row.some(Boolean))rows.push(row);row=[];}else field+=c;}
  if(field||row.length){row.push(field.trim());rows.push(row);} return rows;
}

function normalizeCsv(text:string):{sourceKind:string;rows:CanonicalRow[]}{
  const parsed=parseCsv(text.replace(/^\uFEFF/,"")); const headers=parsed.shift()??[];
  const objects=parsed.map(cells=>Object.fromEntries(headers.map((h,i)=>[h,cells[i]??""])) as Record<string,string>);
  if(headers.includes("基金代碼")) return {sourceKind:"fund_csv",rows:objects.filter(r=>r["基金代碼"]&&r["基金名稱"]).map(r=>({assetCode:r["基金代碼"],assetName:r["基金名稱"],assetType:"基金",currency:r["計價幣別"]||"TWD",units:num(r["總單位數"]),avgCost:num(r["平均申購淨值"]),marketPrice:num(r["最新淨值"]),costBasisTwd:num(r["總投資成本"]),marketValueTwd:num(r["約當市值"]),pnlTwd:num(r["損益"]),returnPct:num(r["含息參考報酬率"]||r["不含息參考報酬率"]),dividendTwd:num(r["已配息金額"]),valuationDate:r["最新淨值日期"]||null,raw:r}))};
  if(headers.includes("股票名稱")) return {sourceKind:"stock_csv",rows:objects.filter(r=>r["股票名稱"]&&!r["股票名稱"].startsWith("總")).map(r=>({assetCode:null,assetName:r["股票名稱"],assetType:"證券",currency:r["幣別"]||"TWD",units:num(r["股數"]),avgCost:num(r["成交均價"]),marketPrice:num(r["市價"]),costBasisTwd:num(r["付出成本"]),marketValueTwd:num(r["現值"]),pnlTwd:num(r["預估損益"]||r["總損益"]),returnPct:num(r["報酬率"]),dividendTwd:0,valuationDate:null,raw:r}))};
  throw new Error("無法辨識欄位；請使用基金庫存或證券未實現彙總 CSV");
}

function extractOcr(text:string){
  const lines=text.split(/\n+/).map(x=>x.trim()).filter(Boolean); const ci=lines.findIndex(x=>/^(?:[A-Z]\d{5}|\d{4,6})$/.test(x.replace(/\s/g,""))); const assetCode=ci>=0?lines[ci].replace(/\s/g,""):"";
  const assetName=ci>=0?(lines.slice(ci+1).find(x=>x.length>4&&!/^[\d,.%+\- TWDUSD]+$/.test(x))??"待校對標的"):(lines.find(x=>x.length>5)??"待校對標的");
  const near=(label:string)=>{const i=lines.findIndex(x=>x.includes(label));const area=i>=0?lines.slice(i,i+4).join(" "):"";return num(area.match(/(?:TWD|USD)?\s*([+\-]?[\d,]+(?:\.\d+)?)/)?.[1]);};
  const rates=[...text.matchAll(/([+\-]?\d+(?:\.\d+)?)\s*%/g)].map(m=>num(m[1])); return {assetCode,assetName,currency:/美金|USD/.test(text)?"USD":"TWD",marketValueTwd:near("參考市值")||near("約當市值"),costBasisTwd:near("投資本金")||near("投資總額"),returnPct:rates.at(-1)??0};
}

export default function Home(){
  const [data,setData]=useState<PortfolioPayload>({...EMPTY_SIDE,positions:[],imports:[],ocrDocuments:[],availableDates:[]}); const [loading,setLoading]=useState(true); const [importing,setImporting]=useState(false); const [ocrFile,setOcrFile]=useState<File|null>(null); const [ocrText,setOcrText]=useState(""); const [ocrProgress,setOcrProgress]=useState(0); const [ocrConfidence,setOcrConfidence]=useState(0); const [ocrBusy,setOcrBusy]=useState(false); const [importDate,setImportDate]=useState(taipeiToday); const [snapshotDate,setSnapshotDate]=useState(taipeiToday); const [snapshotBusy,setSnapshotBusy]=useState(false); const [compareFrom,setCompareFrom]=useState(""); const [compareTo,setCompareTo]=useState(""); const [comparisonResult,setComparisonResult]=useState<{from:string;to:string;data:ComparisonPayload|null}|null>(null); const csvInput=useRef<HTMLInputElement>(null); const imageInput=useRef<HTMLInputElement>(null);
  const load=useCallback(async()=>{try{setData(await fetchPortfolioPayload());}catch(e){toast.error(e instanceof Error?e.message:"資料讀取失敗");}finally{setLoading(false);}},[]);
  useEffect(()=>{let cancelled=false;void fetchPortfolioPayload().then(p=>{if(!cancelled)setData(p);}).catch(e=>{if(!cancelled)toast.error(e instanceof Error?e.message:"資料讀取失敗");}).finally(()=>{if(!cancelled)setLoading(false);});return()=>{cancelled=true;};},[]);
  const totals=useMemo(()=>({cost:data.totals.costBasisTwd,value:data.totals.marketValueTwd,pnl:data.totals.pnlTwd,dividend:data.totals.dividendTwd}),[data.totals]); const totalReturn=totals.cost?(totals.pnl+totals.dividend)/totals.cost*100:0; const allocation=useMemo(()=>Object.entries(data.positions.reduce<Record<string,number>>((a,p)=>{a[p.assetType]=(a[p.assetType]??0)+p.marketValueTwd;return a;},{})).sort((a,b)=>b[1]-a[1]),[data.positions]);
  const latestPurchaseDate=useMemo(()=>data.positions.filter(p=>p.purchaseDateBasis==="exact"&&p.lastPurchaseDate).map(p=>p.lastPurchaseDate as string).sort().at(-1)??null,[data.positions]);
  const latestPurchasePositions=useMemo(()=>latestPurchaseDate?data.positions.filter(p=>p.purchaseDateBasis==="exact"&&p.lastPurchaseDate===latestPurchaseDate):[],[data.positions,latestPurchaseDate]);
  const availableDates=data.availableDates;
  const effectiveCompareTo=compareTo||availableDates[0]||""; const effectiveCompareFrom=compareFrom||availableDates[1]||availableDates[0]||""; const compareDatesPicked=isIsoDate(effectiveCompareFrom)&&isIsoDate(effectiveCompareTo); const compareFresh=!!comparisonResult&&comparisonResult.from===effectiveCompareFrom&&comparisonResult.to===effectiveCompareTo; const compareBusy=compareDatesPicked&&!compareFresh; const comparison=comparisonResult&&compareDatesPicked&&compareFresh?comparisonResult.data:null;
  useEffect(()=>{if(!isIsoDate(effectiveCompareFrom)||!isIsoDate(effectiveCompareTo))return;let cancelled=false;const from=effectiveCompareFrom,to=effectiveCompareTo;fetch(`/api/comparison?from=${encodeURIComponent(from)}&to=${encodeURIComponent(to)}`,{cache:"no-store"}).then(async r=>{const p=await r.json();if(!r.ok)throw new Error(p.error??"日期比較失敗");if(!cancelled)setComparisonResult({from,to,data:p});}).catch(e=>{if(cancelled)return;setComparisonResult({from,to,data:null});toast.error(e instanceof Error?e.message:"日期比較失敗");});return()=>{cancelled=true;};},[effectiveCompareFrom,effectiveCompareTo]);
  async function importCsv(file:File){if(!isIsoDate(importDate)){toast.error("請先選擇統計日期（YYYY-MM-DD）");return;}setImporting(true);try{const text=await file.text(),normalized=normalizeCsv(text);if(!normalized.rows.length)throw new Error("CSV 中沒有可匯入的明細");const digest=await crypto.subtle.digest("SHA-256",await file.arrayBuffer());const fileHash=[...new Uint8Array(digest)].map(b=>b.toString(16).padStart(2,"0")).join("");const r=await fetch("/api/import",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({filename:file.name,fileHash,sourceKind:normalized.sourceKind,asOfDate:importDate,rows:normalized.rows})});const p=await r.json();if(!r.ok)throw new Error(p.error??"匯入失敗");toast.success(`${p.asOfDate} 已匯入 ${p.imported} 筆資料`);await load();}catch(e){toast.error(e instanceof Error?e.message:"匯入失敗");}finally{setImporting(false);if(csvInput.current)csvInput.current.value="";}}
  async function runOcr(file:File){setOcrFile(file);setOcrBusy(true);setOcrText("");setOcrProgress(2);try{const {createWorker}=await import("tesseract.js");const worker=await createWorker("chi_tra+eng",1,{logger:m=>{if(m.progress)setOcrProgress(Math.round(m.progress*100));}});const result=await worker.recognize(file);await worker.terminate();setOcrText(result.data.text);setOcrConfidence(Math.round(result.data.confidence));setOcrProgress(100);toast.success("辨識完成，請先校對再儲存");}catch{toast.error("圖片辨識失敗，請換一張較清晰的截圖");setOcrProgress(0);}finally{setOcrBusy(false);}}
  async function saveOcr(){if(!ocrFile||!ocrText.trim())return;setOcrBusy(true);try{const form=new FormData();form.set("file",ocrFile);form.set("rawText",ocrText);form.set("confidence",String(ocrConfidence));form.set("docType","investment_screenshot");form.set("extractedJson",JSON.stringify(extractOcr(ocrText)));const r=await fetch("/api/ocr",{method:"POST",body:form});const p=await r.json();if(!r.ok)throw new Error(p.error??"儲存失敗");toast.success("OCR 文字與原圖已寫入資料庫");setOcrFile(null);setOcrText("");setOcrProgress(0);await load();}catch(e){toast.error(e instanceof Error?e.message:"儲存失敗");}finally{setOcrBusy(false);}}
  async function saveSnapshot(){setSnapshotBusy(true);try{const r=await fetch("/api/snapshots",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({snapshotDate})});const p=await r.json();if(!r.ok)throw new Error(p.error??"建立統計快照失敗");toast.success(`${snapshotDate} 統計快照已保存`);await load();}catch(e){toast.error(e instanceof Error?e.message:"建立統計快照失敗");}finally{setSnapshotBusy(false);}}
  function exportCsv(){const h=["代碼","名稱","類型","幣別","單位數","成本","投資比重","市值","損益","報酬率","配息","最新購入日","購入日依據","資產分類","投資地區","市值層級","投資風格","產業主題","風險報酬等級"],rows=data.positions.map(p=>[p.assetCode??"",p.assetName,p.assetType,p.currency,p.units,p.costBasisTwd,`${getPositionCostShare(p.costBasisTwd,totals.cost).toFixed(2)}%`,p.marketValueTwd,p.pnlTwd,p.returnPct,p.dividendTwd,p.lastPurchaseDate??"",p.purchaseDateBasis,p.assetCategory??"",p.investRegion??"",p.marketCapTier??"",p.investStyle??"",p.industryTheme??"",p.riskRewardLevel??""]);const csv="\uFEFF"+[h,...rows].map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(",")).join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));a.download=`連薪總署-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(a.href);}
  return <main className="app-shell"><Toaster richColors position="top-center" />
    <header className="topbar"><div className="brand"><span className="brand-mark">薪</span><div><strong>連薪總署</strong><small>INVESTMENT LEDGER</small></div></div><div className="status"><ShieldCheck size={16}/>私人資料庫已連線</div></header>
    <section className="masthead"><div><p className="eyebrow">資產總覽 · {new Date().toLocaleDateString("zh-TW")}</p><h1>把散落的投資紀錄，<br/><em>整理成可追蹤的帳。</em></h1></div><div className="quick-actions"><Button onClick={()=>csvInput.current?.click()} disabled={importing}><FileSpreadsheet/>{importing?"匯入中…":`載入 CSV（${isIsoDate(importDate)?importDate:"未選日期"}）`}</Button><Button variant="outline" onClick={()=>imageInput.current?.click()}><Camera/>圖片 OCR</Button><input ref={csvInput} hidden type="file" accept=".csv,text/csv" onChange={e=>e.target.files?.[0]&&importCsv(e.target.files[0])}/><input ref={imageInput} hidden type="file" accept="image/*" onChange={e=>e.target.files?.[0]&&runOcr(e.target.files[0])}/></div></section>
    <section className="kpi-grid"><article className="kpi primary"><span>參考市值</span><strong>{money.format(totals.value)}</strong><small>{data.positions.length} 筆持倉</small></article><article className="kpi"><span>總投資成本</span><strong>{money.format(totals.cost)}</strong><small>跨基金與證券</small></article><article className={`kpi ${totals.pnl>=0?"gain":"loss"}`}><span>未實現損益</span><strong>{money.format(totals.pnl)}</strong><small>{totals.pnl>=0?<TrendingUp size={14}/>:<TrendingDown size={14}/>} {totalReturn.toFixed(2)}% 含配息估算</small></article><article className="kpi"><span>累計配息</span><strong>{money.format(totals.dividend)}</strong><small>依匯入資料累計</small></article></section>
    <Tabs defaultValue="overview" className="workspace"><TabsList className="tab-list"><TabsTrigger value="overview">分析總覽</TabsTrigger><TabsTrigger value="compare">日期對比</TabsTrigger><TabsTrigger value="positions">持倉明細</TabsTrigger><TabsTrigger value="import">匯入紀錄</TabsTrigger><TabsTrigger value="ocr">OCR 校對</TabsTrigger></TabsList>
      <TabsContent value="overview" className="panel-grid"><section className="paper-card allocation-card"><div className="section-title"><div><span>ALLOCATION</span><h2>資產配置</h2></div><Landmark/></div>{loading?<div className="empty"><LoaderCircle className="spin"/>讀取中</div>:allocation.length?allocation.map(([name,value],i)=><div className="allocation" key={name}><div><b>{name}</b><span>{money.format(value)}</span></div><div className="bar"><i style={{width:`${totals.value?value/totals.value*100:0}%`,background:i?"#e86d4b":"#173b5f"}}/></div><small>{totals.value?(value/totals.value*100).toFixed(1):0}%</small></div>):<EmptyState/>}</section><section className="paper-card insight-card"><div className="section-title"><div><span>CHECKPOINT</span><h2>資料品質</h2></div><Database/></div><div className="quality-row"><span>CSV 匯入批次</span><b>{data.imports.length}</b></div><div className="quality-row"><span>OCR 已校對圖片</span><b>{data.ocrDocuments.length}</b></div><div className="quality-row"><span>最新估值日期</span><b>{data.positions.find(p=>p.valuationDate)?.valuationDate??"尚無資料"}</b></div><div className="notice"><CheckCircle2/>同一份 CSV 以檔案雜湊防止重複計算；OCR 必須人工校對後才入庫。</div></section></TabsContent>
      <TabsContent value="compare" className="compare-stack"><section className="paper-card snapshot-card"><div className="section-title"><div><span>STATISTICS DATE</span><h2>儲存統計快照</h2></div><CalendarDays/></div><p>在完成一次資料匯入後，保存當日全組合數字；同一天只能保存一次，避免比較基準被覆寫。</p><div className="snapshot-action"><Input type="date" value={snapshotDate} onChange={e=>setSnapshotDate(e.target.value)} aria-label="統計資料日期"/><Button onClick={saveSnapshot} disabled={snapshotBusy||!data.positions.length}>{snapshotBusy?<LoaderCircle className="spin"/>:<Save/>}保存此日統計</Button></div></section><section className="paper-card comparison-card"><div className="section-title"><div><span>DELTA VIEW</span><h2>差異金額對比</h2></div><GitCompareArrows/></div>{availableDates.length?<><div className="compare-selects"><label>基準日<Select value={effectiveCompareFrom} onValueChange={setCompareFrom}><SelectTrigger><SelectValue placeholder="選擇日期"/></SelectTrigger><SelectContent>{availableDates.map(date=><SelectItem value={date} key={`from-${date}`}>{date}</SelectItem>)}</SelectContent></Select></label><label>對比日<Select value={effectiveCompareTo} onValueChange={setCompareTo}><SelectTrigger><SelectValue placeholder="選擇日期"/></SelectTrigger><SelectContent>{availableDates.map(date=><SelectItem value={date} key={`to-${date}`}>{date}</SelectItem>)}</SelectContent></Select></label></div>{compareBusy?<div className="empty"><LoaderCircle className="spin"/><b>比較中</b><span>正在還原兩個統計日期當日的持倉組合。</span></div>:comparison?<><div className="delta-row" key="position-count"><span>持倉筆數</span><div><b>{comparison.from.totals.positionCount}</b><i>→</i><b>{comparison.to.totals.positionCount}</b></div><strong className={comparison.to.totals.positionCount-comparison.from.totals.positionCount>=0?"positive":"negative"}>{comparison.to.totals.positionCount-comparison.from.totals.positionCount>=0?"+":""}{comparison.to.totals.positionCount-comparison.from.totals.positionCount}</strong></div>{comparison.metrics.map(metric=><div className="delta-row" key={metric.key}><span>{metric.label}</span><div><b>{money.format(metric.from)}</b><i>→</i><b>{money.format(metric.to)}</b></div><strong className={metric.delta>=0?"positive":"negative"}>{metric.delta>=0?"+":""}{money.format(metric.delta)}</strong></div>)}<div className="compare-note">PRODUCTION TOTALS：基準日 {comparison.from.asOfDate??"未選日期"}（資料日至 {comparison.from.dataAsOf??"－"}）：{importSources(comparison.from)}。對比日 {comparison.to.asOfDate??"未選日期"}（資料日至 {comparison.to.dataAsOf??"－"}）：{importSources(comparison.to)}。</div></>:<div className="empty"><GitCompareArrows/><b>請選擇兩個統計日期</b><span>日期需已有套用的 CSV 匯入批次。</span></div>}</>:<div className="empty"><CalendarDays/><b>尚無統計日期</b><span>先在「匯入紀錄」選好統計日期並載入 CSV；有兩個以上日期後即可比較。</span></div>}</section></TabsContent>
      <TabsContent value="positions" className="compare-stack">
        <section className="paper-card"><div className="section-title"><div><span>LATEST PURCHASE</span><h2>最新購入項目分類</h2></div><CalendarDays/></div>
          {latestPurchaseDate?<><p className="muted">只採用來源明確提供的購入／申購／交易日期；最新日期為 <b>{latestPurchaseDate}</b>。</p><div className="history-list">{latestPurchasePositions.map(p=><div key={`latest-${p.id}`}><CheckCircle2/><span><b>{p.assetName}</b><small>{classificationLabels(p).join(" · ")||"尚無分類"}</small></span></div>)}</div></>:<div className="notice"><ShieldCheck/>目前匯入來源沒有可驗證的購入日期，因此不以統計日或估值日代替「購入日」。分類仍會顯示在下方持倉明細。</div>}
        </section>
        <PortfolioCostCharts positions={data.positions} totalCostBasisTwd={totals.cost}/>
        <section className="paper-card table-card"><div className="section-title table-title"><div><span>LEDGER</span><h2>持倉明細</h2></div><Button variant="outline" size="sm" onClick={exportCsv} disabled={!data.positions.length}><ArrowDownToLine/>匯出</Button></div><div className="table-scroll"><Table><TableHeader><TableRow><TableHead>標的</TableHead><TableHead>分類</TableHead><TableHead>類型</TableHead><TableHead className="num">成本</TableHead><TableHead className="num">投資比重</TableHead><TableHead className="num">市值</TableHead><TableHead className="num">損益</TableHead><TableHead className="num">報酬率</TableHead></TableRow></TableHeader><TableBody>{data.positions.map(p=><TableRow key={p.id}><TableCell><b>{p.assetName}</b><small>{p.assetCode||p.sourceKind}{p.lastPurchaseDate?` · 購入 ${p.lastPurchaseDate}`:" · 購入日未知"}</small></TableCell><TableCell><div className="classification-chips">{classificationLabels(p).map(label=><Badge variant="outline" key={`${p.id}-${label}`}>{label}</Badge>)}{!classificationLabels(p).length&&<Badge variant="outline">待分類</Badge>}</div></TableCell><TableCell><Badge variant="outline">{p.assetType}</Badge></TableCell><TableCell className="num">{money.format(p.costBasisTwd)}</TableCell><TableCell className="num cost-share">{getPositionCostShare(p.costBasisTwd,totals.cost).toFixed(2)}%</TableCell><TableCell className="num">{money.format(p.marketValueTwd)}</TableCell><TableCell className={`num ${p.pnlTwd>=0?"positive":"negative"}`}>{money.format(p.pnlTwd)}</TableCell><TableCell className={`num ${p.returnPct>=0?"positive":"negative"}`}>{p.returnPct.toFixed(2)}%</TableCell></TableRow>)}</TableBody></Table></div>{!data.positions.length&&<EmptyState/>}</section>
      </TabsContent>
      <TabsContent value="import" className="panel-grid"><section className="paper-card drop-card" onClick={()=>csvInput.current?.click()}><Upload/><h2>載入投資 CSV</h2><p>支援「證券未實現彙總」與「帳戶總覽／一般申購」兩種欄位格式，自動轉為統一明細。</p><div className="import-date" onClick={e=>e.stopPropagation()}><label htmlFor="import-as-of-date">統計資料日期 · 本次 CSV 的數字歸到這一天</label><Input id="import-as-of-date" type="date" value={importDate} max={taipeiToday()} onChange={e=>setImportDate(e.target.value)} aria-label="匯入統計資料日期"/></div><Button disabled={importing}>{importing?<LoaderCircle className="spin"/>:<FileSpreadsheet/>}選擇 CSV{isIsoDate(importDate)?`（${importDate}）`:""}</Button></section><section className="paper-card"><div className="section-title"><div><span>HISTORY</span><h2>最近匯入</h2></div><RefreshCw size={20}/></div><div className="history-list">{data.imports.map(item=><div key={item.id}><FileSpreadsheet/><span><b>{item.filename}</b><small>{item.rowCount} 筆 · 統計日期 {item.asOfDate??"－"}{item.status==="pending"?" · 未套用":""} · {new Date(item.createdAt).toLocaleString("zh-TW")}</small></span></div>)}{!data.imports.length&&<p className="muted">尚無匯入紀錄</p>}</div></section></TabsContent>
      <TabsContent value="ocr" className="ocr-grid"><section className="paper-card drop-card ocr-drop" onClick={()=>!ocrBusy&&imageInput.current?.click()}><ScanText/><h2>{ocrFile?.name??"選擇投資截圖"}</h2><p>在瀏覽器內辨識繁體中文與英文，原圖和校對後文字才會送入保存。</p>{ocrBusy&&<Progress value={ocrProgress} className="progress"/>}<Button variant="outline" disabled={ocrBusy}>{ocrBusy?`${ocrProgress}%`:"選擇圖片"}</Button></section><section className="paper-card editor-card"><div className="section-title"><div><span>HUMAN REVIEW</span><h2>文字校對</h2></div>{ocrConfidence>0&&<Badge variant="outline">信心度 {ocrConfidence}%</Badge>}</div><Textarea value={ocrText} onChange={e=>setOcrText(e.target.value)} placeholder="辨識結果會顯示在這裡。請核對代碼、金額、報酬率與日期。"/><div className="editor-footer"><small>儲存時會一併記錄解析欄位與原始圖片。</small><Button onClick={saveOcr} disabled={!ocrText.trim()||ocrBusy}>{ocrBusy?<LoaderCircle className="spin"/>:<Database/>}校對完成並入庫</Button></div></section></TabsContent>
    </Tabs><footer><span>連薪總署</span><p>本工具僅整理使用者提供的紀錄，不構成投資建議；金額仍以金融機構正式對帳單為準。</p></footer></main>;
}
function EmptyState(){return <div className="empty"><Database/><b>尚無資料</b><span>先載入 CSV，即可查看整體成本、市值與損益。</span></div>;}
